# Generated by Django 5.1.5 on 2026-07-26 05:09

import apps.core.fields
import apps.core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='customer code')),
                ('business_name', models.CharField(db_index=True, max_length=200, verbose_name='business name')),
                ('trading_name', models.CharField(blank=True, max_length=200, verbose_name='trading name')),
                ('customer_type', models.CharField(choices=[('PHARMACY', 'Pharmacy'), ('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('HEALTH_CENTRE', 'Health centre'), ('NGO', 'NGO / humanitarian organisation'), ('GOVERNMENT', 'Government / public sector'), ('WHOLESALER', 'Other wholesaler'), ('OTHER', 'Other')], default='PHARMACY', max_length=20, verbose_name='customer type')),
                ('nif', models.CharField(blank=True, db_index=True, help_text="Tax identification number (Numéro d'Identification Fiscale).", max_length=20, validators=[apps.core.validators.validate_nif], verbose_name='NIF')),
                ('rc_number', models.CharField(blank=True, max_length=40, verbose_name='trade register number')),
                ('pharmacy_licence', models.CharField(blank=True, help_text='Operating licence issued by the Ministry of Health.', max_length=64, verbose_name='pharmacy licence number')),
                ('licence_expiry', models.DateField(blank=True, null=True, verbose_name='licence expiry')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='contact person')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_burundi_phone], verbose_name='telephone')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, verbose_name='alternate telephone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('city', models.CharField(db_index=True, default='Bujumbura', max_length=80, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=80, verbose_name='province')),
                ('country', models.CharField(default='Burundi', max_length=80, verbose_name='country')),
                ('credit_limit', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), help_text='Maximum outstanding balance permitted. Zero means cash only.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='credit limit')),
                ('outstanding_balance', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='outstanding balance')),
                ('payment_terms', models.CharField(choices=[('CASH', 'Cash on delivery'), ('NET_7', '7 days'), ('NET_15', '15 days'), ('NET_30', '30 days'), ('NET_45', '45 days'), ('NET_60', '60 days'), ('NET_90', '90 days')], default='CASH', max_length=10, verbose_name='payment terms')),
                ('credit_blocked', models.BooleanField(default=False, help_text='Blocks all credit sales regardless of the available limit.', verbose_name='credit blocked')),
                ('credit_block_reason', models.CharField(blank=True, max_length=255, verbose_name='reason for credit block')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='standard discount (%)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('PENDING', 'Pending approval')], db_index=True, default='ACTIVE', max_length=16, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('first_sale_at', models.DateTimeField(blank=True, null=True, verbose_name='first sale')),
                ('last_sale_at', models.DateTimeField(blank=True, null=True, verbose_name='last sale')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ('business_name',),
            },
        ),
        migrations.CreateModel(
            name='CreditLimitChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_limit', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='previous limit')),
                ('new_limit', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='new limit')),
                ('reason', models.CharField(max_length=255, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_limit_changes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_limit_history', to='partners.customer')),
            ],
            options={
                'verbose_name': 'credit limit change',
                'verbose_name_plural': 'credit limit changes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='role')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telephone')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary contact')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partners.customer', verbose_name='customer')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer contact',
                'verbose_name_plural': 'customer contacts',
                'ordering': ('-is_primary', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='supplier code')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='supplier name')),
                ('nif', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='NIF')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='contact person')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telephone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='country')),
                ('payment_terms', models.CharField(choices=[('CASH', 'Cash on delivery'), ('NET_7', '7 days'), ('NET_15', '15 days'), ('NET_30', '30 days'), ('NET_45', '45 days'), ('NET_60', '60 days'), ('NET_90', '90 days')], default='NET_30', max_length=10, verbose_name='payment terms')),
                ('currency', models.CharField(default='BIF', help_text='Currency in which this supplier invoices (BIF, USD, EUR).', max_length=3, verbose_name='invoicing currency')),
                ('lead_time_days', models.PositiveIntegerField(default=30, help_text='Used to compute reorder timing.', verbose_name='average lead time (days)')),
                ('bank_name', models.CharField(blank=True, max_length=120, verbose_name='bank')),
                ('bank_account', models.CharField(blank=True, max_length=64, verbose_name='bank account')),
                ('swift_code', models.CharField(blank=True, max_length=16, verbose_name='SWIFT / BIC')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('PENDING', 'Pending approval')], db_index=True, default='ACTIVE', max_length=16, verbose_name='status')),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved suppliers may be selected on a purchase order.', verbose_name='approved supplier')),
                ('approval_notes', models.TextField(blank=True, verbose_name='approval notes')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status', 'business_name'], name='idx_customer_status_name'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type', 'status'], name='idx_customer_type'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit__gte', Decimal('0'))), name='customer_credit_limit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('nif', ''), _negated=True)), fields=('nif',), name='unique_active_customer_nif'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['status', 'name'], name='idx_supplier_status_name'),
        ),
    ]
