# Generated by Django 5.1.5 on 2026-07-26 05:09

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='order number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SENT', 'Sent to supplier'), ('PARTIALLY_RECEIVED', 'Partially received'), ('RECEIVED', 'Fully received'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20, verbose_name='status')),
                ('order_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='order date')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='expected delivery')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='actual delivery')),
                ('subtotal', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='subtotal')),
                ('discount_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='discount')),
                ('tax_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='VAT')),
                ('freight_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='freight')),
                ('customs_duty', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='customs duty')),
                ('other_charges', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='other charges')),
                ('total_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='total')),
                ('currency', models.CharField(default='BIF', max_length=3, verbose_name='currency')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Rate applied when the supplier invoices in foreign currency.', max_digits=18, verbose_name='exchange rate to BIF')),
                ('payment_terms', models.CharField(blank=True, max_length=10, verbose_name='payment terms')),
                ('supplier_reference', models.CharField(blank=True, max_length=64, verbose_name='supplier reference')),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=64, verbose_name='supplier invoice number')),
                ('supplier_invoice_date', models.DateField(blank=True, null=True, verbose_name='supplier invoice date')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='rejection reason')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent to supplier at')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='cancellation reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_orders', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='partners.supplier', verbose_name='supplier')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouse', verbose_name='delivery warehouse')),
            ],
            options={
                'verbose_name': 'purchase order',
                'verbose_name_plural': 'purchase orders',
                'ordering': ('-order_date', '-order_number'),
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='receipt number')),
                ('receipt_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='receipt date')),
                ('delivery_note_number', models.CharField(blank=True, max_length=64, verbose_name='supplier delivery note')),
                ('quality_checked', models.BooleanField(default=False, verbose_name='quality checked')),
                ('quality_notes', models.TextField(blank=True, verbose_name='quality notes')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('quality_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to=settings.AUTH_USER_MODEL, verbose_name='quality checked by')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to=settings.AUTH_USER_MODEL, verbose_name='received by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='inventory.warehouse', verbose_name='warehouse')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.purchaseorder', verbose_name='purchase order')),
            ],
            options={
                'verbose_name': 'goods receipt',
                'verbose_name_plural': 'goods receipts',
                'ordering': ('-receipt_date',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1, verbose_name='line number')),
                ('quantity_ordered', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity ordered')),
                ('quantity_received', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity received')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='unit cost')),
                ('discount_percent', apps.core.fields.PercentField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='discount (%)')),
                ('discount_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='discount')),
                ('tax_rate', apps.core.fields.PercentField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='VAT rate (%)')),
                ('tax_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='VAT')),
                ('line_total', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='line total')),
                ('expected_expiry_date', models.DateField(blank=True, help_text='Minimum acceptable expiry date for this line.', null=True, verbose_name='expected expiry')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='catalog.medicine', verbose_name='product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder', verbose_name='purchase order')),
            ],
            options={
                'verbose_name': 'purchase order line',
                'verbose_name_plural': 'purchase order lines',
                'ordering': ('purchase_order', 'line_number'),
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=64, verbose_name='batch number')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='manufacturing date')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
                ('quantity_received', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity received')),
                ('quantity_rejected', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity rejected')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='rejection reason')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='unit cost')),
                ('landed_unit_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='landed unit cost')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='inventory.stockbatch', verbose_name='batch created')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.goodsreceipt', verbose_name='receipt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='catalog.medicine', verbose_name='product')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchasing.purchaseorderline', verbose_name='order line')),
            ],
            options={
                'verbose_name': 'goods receipt line',
                'verbose_name_plural': 'goods receipt lines',
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', '-order_date'], name='idx_po_supplier_date'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', '-order_date'], name='idx_po_status_date'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0'))), name='po_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', Decimal('0'))), name='po_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_ordered__gt', Decimal('0'))), name='po_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__lte', models.F('quantity_ordered'))), name='po_line_receipt_within_order'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gt', Decimal('0'))), name='receipt_line_quantity_positive'),
        ),
    ]
