# Generated by Django 5.1.5 on 2026-08-05 15:49

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, help_text='The number the supplier put on their document.', max_length=64, verbose_name='invoice number')),
                ('reference', models.CharField(db_index=True, help_text='Our own sequential reference for this payable.', max_length=32, unique=True, verbose_name='internal reference')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='AWAITING_PAYMENT', max_length=20, verbose_name='status')),
                ('invoice_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='invoice date')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='date received')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='due date')),
                ('subtotal', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='subtotal')),
                ('tax_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='VAT')),
                ('freight_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='freight')),
                ('customs_duty', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='customs duty')),
                ('other_charges', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='other charges')),
                ('total_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='total')),
                ('paid_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='amount paid')),
                ('balance_due', apps.core.fields.MoneyField(db_index=True, decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='balance due')),
                ('currency', models.CharField(default='BIF', max_length=3, verbose_name='currency')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Rate applied when the supplier invoices in foreign currency.', max_digits=18, verbose_name='exchange rate to BIF')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='cancellation reason')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Optional: the order this invoice bills, for three-way matching.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='purchasing.purchaseorder', verbose_name='purchase order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='partners.supplier', verbose_name='supplier')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'supplier invoice',
                'verbose_name_plural': 'supplier invoices',
                'ordering': ('-invoice_date', '-reference'),
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='payment reference')),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='payment date')),
                ('amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='amount')),
                ('allocated_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='allocated amount')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('MOBILE_MONEY', 'Mobile money'), ('CARD', 'Bank card'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20, verbose_name='payment method')),
                ('payment_reference', models.CharField(blank=True, help_text='Cheque number or internal transaction number.', max_length=64, verbose_name='payment / transaction number')),
                ('bank_reference', models.CharField(blank=True, help_text='Transfer reference or mobile money confirmation code.', max_length=64, verbose_name='bank / mobile money reference')),
                ('bank_account', models.CharField(blank=True, max_length=120, verbose_name='account debited')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='reversed')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.CharField(blank=True, max_length=255, verbose_name='reversal reason')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to=settings.AUTH_USER_MODEL, verbose_name='paid by')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='partners.supplier', verbose_name='supplier')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'supplier payment',
                'verbose_name_plural': 'supplier payments',
                'ordering': ('-payment_date', '-reference'),
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='allocated amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_allocations', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='purchasing.supplierpayment', verbose_name='payment')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='purchasing.supplierinvoice', verbose_name='supplier invoice')),
            ],
            options={
                'verbose_name': 'supplier payment allocation',
                'verbose_name_plural': 'supplier payment allocations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['supplier', '-invoice_date'], name='idx_supinv_supplier_date'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['status', 'due_date'], name='idx_supinv_status_due'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0'))), name='supplier_invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', Decimal('0'))), name='supplier_invoice_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('supplier', 'invoice_number'), name='unique_supplier_invoice_number'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', '-payment_date'], name='idx_suppay_supplier_date'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['-payment_date'], name='idx_suppay_date'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='supplier_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__lte', models.F('amount'))), name='supplier_payment_allocation_within_amount'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='supplier_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'supplier_invoice'), name='unique_supplier_payment_invoice_allocation'),
        ),
    ]
