# Generated by Django 5.1.5 on 2026-07-26 05:09

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0002_initial'),
        ('invoicing', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='sale number')),
                ('sale_type', models.CharField(choices=[('CASH', 'Cash sale'), ('CREDIT', 'Credit sale')], db_index=True, default='CASH', max_length=10, verbose_name='sale type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('PARTIALLY_RETURNED', 'Partially returned')], db_index=True, default='DRAFT', max_length=20, verbose_name='status')),
                ('sale_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='sale date')),
                ('subtotal', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='subtotal')),
                ('discount_percent', apps.core.fields.PercentField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='global discount (%)')),
                ('discount_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='discount')),
                ('tax_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='VAT')),
                ('total_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='total')),
                ('total_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='total cost of goods sold')),
                ('delivery_address', models.CharField(blank=True, max_length=255, verbose_name='delivery address')),
                ('delivery_note_number', models.CharField(blank=True, max_length=32, verbose_name='delivery note')),
                ('customer_order_reference', models.CharField(blank=True, max_length=64, verbose_name='customer order reference')),
                ('credit_override_reason', models.CharField(blank=True, max_length=255, verbose_name='credit override reason')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='cancellation reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('credit_override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_overrides', to=settings.AUTH_USER_MODEL, verbose_name='credit override authorised by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='partners.customer', verbose_name='customer')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='salesperson')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
                'ordering': ('-sale_date',),
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1, verbose_name='line number')),
                ('quantity', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity')),
                ('quantity_returned', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity returned')),
                ('unit_price', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='unit price')),
                ('discount_percent', apps.core.fields.PercentField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='discount (%)')),
                ('discount_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='discount')),
                ('tax_rate', apps.core.fields.PercentField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='VAT rate (%)')),
                ('tax_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='VAT')),
                ('line_subtotal', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='subtotal')),
                ('line_total', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='line total')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='unit cost')),
                ('line_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='line cost')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalog.medicine', verbose_name='product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'sale line',
                'verbose_name_plural': 'sale lines',
                'ordering': ('sale', 'line_number'),
            },
        ),
        migrations.CreateModel(
            name='SaleLineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=64, verbose_name='batch number')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
                ('quantity', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity')),
                ('quantity_returned', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity returned')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='unit cost')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='inventory.stockbatch', verbose_name='batch')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='sales.saleline', verbose_name='sale line')),
            ],
            options={
                'verbose_name': 'sale line batch allocation',
                'verbose_name_plural': 'sale line batch allocations',
                'ordering': ('sale_line', 'expiry_date'),
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='return number')),
                ('return_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='return date')),
                ('reason', models.CharField(max_length=255, verbose_name='reason')),
                ('total_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='refunded amount')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_returns', to='invoicing.invoice', verbose_name='credit note')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='partners.customer', verbose_name='customer')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to=settings.AUTH_USER_MODEL, verbose_name='processed by')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale', verbose_name='original sale')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sale return',
                'verbose_name_plural': 'sale returns',
                'ordering': ('-return_date',),
            },
        ),
        migrations.CreateModel(
            name='SaleReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity returned')),
                ('unit_price', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='unit price')),
                ('refund_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='refund')),
                ('restock', models.BooleanField(default=False, help_text='Only when storage conditions were verifiably maintained.', verbose_name='return to sellable stock')),
                ('condition_notes', models.CharField(blank=True, max_length=255, verbose_name='condition on return')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='inventory.stockbatch', verbose_name='batch')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='sales.saleline', verbose_name='original line')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salereturn', verbose_name='return')),
            ],
            options={
                'verbose_name': 'sale return line',
                'verbose_name_plural': 'sale return lines',
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', '-sale_date'], name='idx_sale_customer_date'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', '-sale_date'], name='idx_sale_status_date'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-sale_date'], name='idx_sale_date'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0'))), name='sale_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='sale_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_returned__lte', models.F('quantity'))), name='sale_line_return_within_quantity'),
        ),
        migrations.AddIndex(
            model_name='salelinebatch',
            index=models.Index(fields=['batch'], name='idx_slb_batch'),
        ),
        migrations.AddIndex(
            model_name='salelinebatch',
            index=models.Index(fields=['batch_number'], name='idx_slb_batch_number'),
        ),
        migrations.AddConstraint(
            model_name='salereturnline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='return_line_quantity_positive'),
        ),
    ]
