# Generated by Django 5.1.5 on 2026-08-01 16:36

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='receipt number')),
                ('customer_name', models.CharField(max_length=200, verbose_name='customer name')),
                ('customer_nif', models.CharField(blank=True, max_length=20, verbose_name='customer NIF')),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='issued at')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('MOBILE_MONEY', 'Mobile money'), ('CARD', 'Bank card'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='payment method')),
                ('payment_reference', models.CharField(blank=True, help_text='Mobile money code, card authorisation or transfer reference.', max_length=64, verbose_name='payment reference')),
                ('amount_tendered', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='amount tendered')),
                ('change_given', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='change given')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('print_count', models.PositiveIntegerField(default=0, verbose_name='times printed')),
                ('last_printed_at', models.DateTimeField(blank=True, null=True, verbose_name='last printed')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='cancellation reason')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_receipts', to='partners.customer', verbose_name='customer')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_receipts', to=settings.AUTH_USER_MODEL, verbose_name='issued by')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='sales.sale', verbose_name='sale')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sales receipt',
                'verbose_name_plural': 'sales receipts',
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['customer', '-issued_at'], name='idx_receipt_customer_date'), models.Index(fields=['-issued_at'], name='idx_receipt_date')],
            },
        ),
    ]
