# Generated by Django 5.1.5 on 2026-07-26 05:09

import apps.accounts.models
import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='code')),
                ('name_fr', models.CharField(max_length=150, verbose_name='name (French)')),
                ('name_en', models.CharField(max_length=150, verbose_name='name (English)')),
                ('description_fr', models.TextField(blank=True, verbose_name='description (French)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (English)')),
                ('module', models.CharField(choices=[('CATALOG', 'Medicine catalog'), ('INVENTORY', 'Inventory'), ('SALES', 'Sales'), ('INVOICING', 'Invoicing'), ('PURCHASING', 'Purchasing'), ('PARTNERS', 'Customers & suppliers'), ('REPORTING', 'Reporting'), ('ADMINISTRATION', 'Administration'), ('AUDIT', 'Audit & compliance')], db_index=True, max_length=32, verbose_name='module')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='sensitive')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ('module', 'code'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_burundi_phone], verbose_name='telephone')),
                ('employee_code', models.CharField(blank=True, max_length=32, verbose_name='employee code')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='job title')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5, verbose_name='preferred language')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='admin site access')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='suspended')),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='MFA enabled')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='must change password')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='password changed at')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('last_name', 'first_name'),
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'password history entry',
                'verbose_name_plural': 'password history',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='code')),
                ('name_fr', models.CharField(max_length=100, verbose_name='name (French)')),
                ('name_en', models.CharField(max_length=100, verbose_name='name (English)')),
                ('description_fr', models.TextField(blank=True, verbose_name='description (French)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (English)')),
                ('is_system', models.BooleanField(default=False, editable=False, verbose_name='system role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('inherits_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='accounts.role', verbose_name='inherits from')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ('name_fr',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.role', verbose_name='roles'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user session',
                'verbose_name_plural': 'user sessions',
                'ordering': ('-last_seen_at',),
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_suspended'], name='accounts_us_is_acti_c45a13_idx'),
        ),
    ]
