# Generated by Django 5.1.5 on 2026-08-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('CATALOG', 'Medicine catalog'), ('INVENTORY', 'Inventory'), ('SALES', 'Sales'), ('INVOICING', 'Invoicing'), ('PURCHASING', 'Purchasing'), ('PARTNERS', 'Customers & suppliers'), ('ACCOUNTING', 'Accounting'), ('REPORTING', 'Reporting'), ('ADMINISTRATION', 'Administration'), ('AUDIT', 'Audit & compliance')], db_index=True, max_length=32, verbose_name='module'),
        ),
    ]
