# Generated by Django 5.1.5 on 2026-07-26 05:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='key')),
                ('label', models.CharField(blank=True, max_length=128, verbose_name='label')),
                ('prefix', models.CharField(default='', max_length=32, verbose_name='prefix')),
                ('padding', models.PositiveSmallIntegerField(default=6, verbose_name='padding')),
                ('scope', models.CharField(choices=[('GLOBAL', 'Continuous'), ('YEARLY', 'Reset annually'), ('MONTHLY', 'Reset monthly')], default='YEARLY', max_length=16, verbose_name='reset scope')),
                ('current_value', models.BigIntegerField(default=0, verbose_name='current value')),
                ('period_key', models.CharField(blank=True, editable=False, max_length=16)),
            ],
            options={
                'verbose_name': 'document sequence',
                'verbose_name_plural': 'document sequences',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('actor_username', models.CharField(blank=True, editable=False, max_length=254)),
                ('actor_role', models.CharField(blank=True, editable=False, max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Failed login'), ('LOGOUT', 'Logout'), ('LOCKOUT', 'Account lockout'), ('PASSWORD_CHANGE', 'Password change'), ('PASSWORD_RESET', 'Password reset'), ('PERMISSION_CHANGE', 'Permission change'), ('APPROVE', 'Approval'), ('REJECT', 'Rejection'), ('CANCEL', 'Cancellation'), ('POST', 'Posting'), ('PRINT', 'Print / reprint'), ('EXPORT', 'Data export'), ('STOCK_MOVEMENT', 'Stock movement'), ('PRICE_CHANGE', 'Price change')], db_index=True, editable=False, max_length=32)),
                ('entity_type', models.CharField(db_index=True, editable=False, max_length=100)),
                ('entity_id', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('entity_label', models.CharField(blank=True, editable=False, max_length=255)),
                ('previous_value', models.JSONField(blank=True, editable=False, null=True)),
                ('new_value', models.JSONField(blank=True, editable=False, null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list, editable=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user_agent', models.CharField(blank=True, editable=False, max_length=512)),
                ('request_id', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('notes', models.TextField(blank=True, editable=False)),
                ('previous_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('entry_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('actor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ('-timestamp', '-id'),
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__244637_idx'), models.Index(fields=['actor', '-timestamp'], name='core_auditl_actor_i_cba5aa_idx'), models.Index(fields=['action', '-timestamp'], name='core_auditl_action_f07419_idx')],
            },
        ),
    ]
