# Generated by Django 5.1.5 on 2026-08-05 15:49

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='name (English)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('is_cost_of_goods', models.BooleanField(default=False, help_text='Shipping, clearing and similar costs that attach to stock.', verbose_name='counts toward cost of goods')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='display order')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'expense category',
                'verbose_name_plural': 'expense categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='reference')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECORDED', 'Recorded'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECORDED', max_length=16, verbose_name='status')),
                ('description', models.CharField(help_text='What this cost was for.', max_length=255, verbose_name='description')),
                ('notes', models.TextField(blank=True, help_text='Fuller explanation: what it covered, why it was needed, who authorised it.', verbose_name='notes')),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='When the cost was incurred.', verbose_name='expense date')),
                ('paid_date', models.DateField(blank=True, db_index=True, help_text='When money actually left the business.', null=True, verbose_name='date paid')),
                ('amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='amount')),
                ('tax_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='VAT included')),
                ('currency', models.CharField(default='BIF', max_length=3, verbose_name='currency')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('MOBILE_MONEY', 'Mobile money'), ('CARD', 'Bank card'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='payment method')),
                ('payment_reference', models.CharField(blank=True, help_text='Cheque number, transfer reference or mobile money code.', max_length=64, verbose_name='payment reference')),
                ('payee', models.CharField(blank=True, max_length=200, verbose_name='paid to')),
                ('receipt_number', models.CharField(blank=True, max_length=64, verbose_name='supplier receipt number')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='cancellation reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='purchasing.purchaseorder', verbose_name='related purchase order')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='partners.supplier', verbose_name='supplier')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.expensecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'ordering': ('-expense_date', '-reference'),
                'indexes': [models.Index(fields=['category', '-expense_date'], name='idx_expense_cat_date'), models.Index(fields=['status', '-expense_date'], name='idx_expense_status_date'), models.Index(fields=['-paid_date'], name='idx_expense_paid_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='expense_amount_positive'), models.CheckConstraint(condition=models.Q(('tax_amount__lte', models.F('amount'))), name='expense_tax_within_amount')],
            },
        ),
    ]
