"""
Move expense categories onto the paired-language columns.

Written by hand rather than autogenerated so the existing names survive: the
old `name`/`description` columns already hold French text, so they are
*renamed* into `name_fr`/`description_fr` instead of being dropped and
recreated. An add-and-drop would have silently emptied every category label on
an installation that had already seeded them.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        # Rename, so the French text already in these columns is carried over.
        migrations.RenameField(
            model_name="expensecategory",
            old_name="name",
            new_name="name_fr",
        ),
        migrations.RenameField(
            model_name="expensecategory",
            old_name="description",
            new_name="description_fr",
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="description (English)"
            ),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="name_fr",
            field=models.CharField(max_length=120, verbose_name="name (French)"),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="description_fr",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="description (French)"
            ),
        ),
        migrations.AlterModelOptions(
            name="expensecategory",
            options={
                "ordering": ("sort_order", "name_fr"),
                "verbose_name": "expense category",
                "verbose_name_plural": "expense categories",
            },
        ),
    ]
