# Generated by Django 5.1.5 on 2026-07-26 05:09

import apps.core.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Goods receipt'), ('ISSUE', 'Sales issue'), ('SALE_RETURN', 'Customer return'), ('PURCHASE_RETURN', 'Return to supplier'), ('TRANSFER_OUT', 'Transfer out'), ('TRANSFER_IN', 'Transfer in'), ('ADJUSTMENT_IN', 'Positive adjustment'), ('ADJUSTMENT_OUT', 'Negative adjustment'), ('DAMAGE', 'Damage write-off'), ('EXPIRY', 'Expiry write-off'), ('DISPOSAL', 'Disposal'), ('OPENING', 'Opening balance')], db_index=True, max_length=20, verbose_name='movement type')),
                ('quantity_delta', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity change')),
                ('balance_after', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='batch balance after movement')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='unit cost at movement')),
                ('total_value', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='movement value')),
                ('source_type', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='source document type')),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='source document id')),
                ('source_reference', models.CharField(blank=True, max_length=64, verbose_name='source reference')),
                ('performed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='performed at')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ('-performed_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity')),
                ('source_type', models.CharField(db_index=True, max_length=64)),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'stock reservation',
                'verbose_name_plural': 'stock reservations',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('city', models.CharField(default='Bujumbura', max_length=80, verbose_name='city')),
                ('is_default', models.BooleanField(default=False, verbose_name='default warehouse')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_cold_chain', models.BooleanField(default=False, verbose_name='cold chain capable')),
            ],
            options={
                'verbose_name': 'warehouse',
                'verbose_name_plural': 'warehouses',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=64, verbose_name='batch number')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='manufacturing date')),
                ('expiry_date', models.DateField(db_index=True, verbose_name='expiry date')),
                ('quantity_received', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='quantity received')),
                ('quantity_remaining', apps.core.fields.QuantityField(db_index=True, decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity remaining')),
                ('quantity_reserved', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity reserved')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='unit purchase cost')),
                ('landed_unit_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), help_text='Unit cost including freight, duty and clearing charges.', max_digits=18, verbose_name='landed unit cost')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('QUARANTINED', 'Quarantined'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('RECALLED', 'Recalled'), ('DEPLETED', 'Depleted'), ('DISPOSED', 'Disposed')], db_index=True, default='ACTIVE', max_length=16, verbose_name='status')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='received at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.medicine', verbose_name='product')),
            ],
            options={
                'verbose_name': 'stock batch',
                'verbose_name_plural': 'stock batches',
                'ordering': ('expiry_date', 'received_at'),
            },
        ),
    ]
