# Generated by Django 5.1.5 on 2026-07-26 05:09

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1, verbose_name='line number')),
                ('product_code', models.CharField(max_length=32, verbose_name='product code')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('batch_numbers', models.CharField(blank=True, help_text='Comma-separated batches issued for this line.', max_length=255, verbose_name='batch numbers')),
                ('expiry_dates', models.CharField(blank=True, max_length=255, verbose_name='expiry dates')),
                ('quantity', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity')),
                ('unit_of_measure', models.CharField(blank=True, max_length=16, verbose_name='unit')),
                ('unit_price', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='unit price')),
                ('discount_percent', apps.core.fields.PercentField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='discount (%)')),
                ('discount_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='discount')),
                ('tax_rate', apps.core.fields.PercentField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='VAT rate (%)')),
                ('tax_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='VAT')),
                ('line_subtotal', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='subtotal')),
                ('line_total', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='line total')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='unit cost at sale')),
            ],
            options={
                'verbose_name': 'invoice line',
                'verbose_name_plural': 'invoice lines',
                'ordering': ('invoice', 'line_number'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='payment reference')),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='payment date')),
                ('amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='amount')),
                ('allocated_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='allocated amount')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('MOBILE_MONEY', 'Mobile money'), ('CARD', 'Bank card'), ('CREDIT_NOTE', 'Credit note offset'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='payment method')),
                ('bank_reference', models.CharField(blank=True, help_text='Cheque number, transfer reference or mobile money code.', max_length=64, verbose_name='bank / transaction reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='reversed')),
                ('reversal_reason', models.CharField(blank=True, max_length=255, verbose_name='reversal reason')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ('-payment_date',),
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='allocated amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'payment allocation',
                'verbose_name_plural': 'payment allocations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='invoice number')),
                ('invoice_type', models.CharField(choices=[('STANDARD', 'Invoice'), ('PROFORMA', 'Proforma invoice'), ('CREDIT_NOTE', 'Credit note'), ('DEBIT_NOTE', 'Debit note')], db_index=True, default='STANDARD', max_length=16, verbose_name='document type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='status')),
                ('customer_name', models.CharField(max_length=200, verbose_name='customer name')),
                ('customer_nif', models.CharField(blank=True, max_length=20, verbose_name='customer NIF')),
                ('customer_address', models.CharField(blank=True, max_length=255, verbose_name='customer address')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='customer telephone')),
                ('invoice_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='invoice date')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='due date')),
                ('payment_terms_days', models.PositiveIntegerField(default=0, verbose_name='payment terms (days)')),
                ('subtotal', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='subtotal before discount')),
                ('discount_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='discount')),
                ('taxable_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='taxable base')),
                ('tax_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='VAT')),
                ('total_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='total')),
                ('paid_amount', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='amount paid')),
                ('balance_due', apps.core.fields.MoneyField(db_index=True, decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='balance due')),
                ('currency', models.CharField(default='BIF', max_length=3, verbose_name='currency')),
                ('is_credit_sale', models.BooleanField(default=False, verbose_name='credit sale')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='external reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('internal_notes', models.TextField(blank=True, help_text='Not printed on the customer-facing document.', verbose_name='internal notes')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='cancellation reason')),
                ('print_count', models.PositiveIntegerField(default=0, verbose_name='times printed')),
                ('last_printed_at', models.DateTimeField(blank=True, null=True, verbose_name='last printed')),
                ('emailed_at', models.DateTimeField(blank=True, null=True, verbose_name='emailed at')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_invoices', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='partners.customer', verbose_name='customer')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='invoicing.invoice', verbose_name='original invoice')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_invoices', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ('-invoice_date', '-invoice_number'),
            },
        ),
    ]
