# Generated by Django 5.1.5 on 2026-08-01 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_initial'),
        ('partners', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalRequestLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation', models.CharField(db_index=True, max_length=32, verbose_name='operation')),
                ('endpoint', models.URLField(max_length=255, verbose_name='endpoint')),
                ('request_body', models.JSONField(blank=True, null=True, verbose_name='request body')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='response body')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP status')),
                ('outcome', models.CharField(choices=[('IN_FLIGHT', 'In flight'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='IN_FLIGHT', max_length=12, verbose_name='outcome')),
                ('error_message', models.TextField(blank=True, verbose_name='error')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'OBR request log',
                'verbose_name_plural': 'OBR request log',
                'ordering': ('-started_at',),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancellation_declared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancellation declared at'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='declaration_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='declaration attempts'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='declared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='declared at'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_signature',
            field=models.CharField(blank=True, db_index=True, help_text='Identifier under which this document is declared to the OBR.', max_length=128, verbose_name='fiscal signature'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not declarable'), ('PENDING', 'Awaiting declaration'), ('DECLARED', 'Declared to OBR'), ('REJECTED', 'Rejected by OBR'), ('CANCELLED', 'Cancellation declared')], db_index=True, default='NOT_REQUIRED', max_length=16, verbose_name='fiscal status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_declaration_error',
            field=models.TextField(blank=True, verbose_name='last declaration error'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='obr_electronic_signature',
            field=models.TextField(blank=True, help_text='Returned by the OBR on acceptance; printed on the customer document.', verbose_name='OBR electronic signature'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='obr_registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OBR registration date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='obr_registered_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='OBR registration number'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['fiscal_status', 'invoice_date'], name='idx_invoice_fiscal_status'),
        ),
        migrations.AddField(
            model_name='fiscalrequestlog',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_requests', to='invoicing.invoice', verbose_name='invoice'),
        ),
        migrations.AddIndex(
            model_name='fiscalrequestlog',
            index=models.Index(fields=['invoice', '-started_at'], name='idx_fiscal_req_invoice'),
        ),
        migrations.AddIndex(
            model_name='fiscalrequestlog',
            index=models.Index(fields=['outcome', '-started_at'], name='idx_fiscal_req_outcome'),
        ),
    ]
