# Generated by Django 5.1.5 on 2026-08-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_fiscalrequestlog_invoice_cancellation_declared_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit_reason_code',
            field=models.CharField(blank=True, choices=[('WRONG_QUANTITY', 'Wrong quantity invoiced'), ('WRONG_PRICE', 'Wrong unit price charged'), ('GOODS_RETURNED', 'Goods returned by customer'), ('GOODS_DAMAGED', 'Goods damaged or defective'), ('DISCOUNT_GRANTED', 'Discount or rebate granted'), ('OTHER', 'Other')], db_index=True, max_length=20, verbose_name='correction reason'),
        ),
    ]
