# Generated by Django 5.1.5 on 2026-08-01 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_invoice_credit_reason_code'),
        ('sales', '0002_salesreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='source_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoice', to='sales.salesreceipt', verbose_name='source receipt'),
        ),
    ]
