# Generated by Django 5.1.5 on 2026-08-03 13:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_invoice_source_receipt'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='receipt number')),
                ('customer_name', models.CharField(max_length=200, verbose_name='customer name')),
                ('customer_nif', models.CharField(blank=True, max_length=20, verbose_name='customer NIF')),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='issued at')),
                ('emailed_at', models.DateTimeField(blank=True, null=True, verbose_name='emailed at')),
                ('print_count', models.PositiveIntegerField(default=0, verbose_name='times printed')),
                ('last_printed_at', models.DateTimeField(blank=True, null=True, verbose_name='last printed')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='cancellation reason')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='partners.customer', verbose_name='customer')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipt', to='invoicing.invoice', verbose_name='invoice')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_payment_receipts', to=settings.AUTH_USER_MODEL, verbose_name='issued by')),
                ('settling_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_issued', to='invoicing.payment', verbose_name='settling payment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment receipt',
                'verbose_name_plural': 'payment receipts',
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['customer', '-issued_at'], name='idx_payreceipt_customer'), models.Index(fields=['-issued_at'], name='idx_payreceipt_date')],
            },
        ),
    ]
