# Generated by Django 5.1.5 on 2026-07-26 05:09

import apps.core.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='code')),
                ('name_fr', models.CharField(max_length=120, verbose_name='name (French)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='name (English)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='parent category')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='country')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='telephone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'manufacturer',
                'verbose_name_plural': 'manufacturers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='code')),
                ('name_fr', models.CharField(max_length=60, verbose_name='name (French)')),
                ('name_en', models.CharField(blank=True, max_length=60, verbose_name='name (English)')),
                ('units_per_pack', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('1'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='units per pack')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_units', to='catalog.unitofmeasure', verbose_name='base unit')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'unit of measure',
                'verbose_name_plural': 'units of measure',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='product code')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='commercial name')),
                ('generic_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='generic name (INN)')),
                ('brand_name', models.CharField(blank=True, max_length=200, verbose_name='brand name')),
                ('strength', models.CharField(blank=True, help_text='For example: 500 mg, 250 mg/5 ml', max_length=64, verbose_name='strength')),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Suspension'), ('INJECTION', 'Injection'), ('INFUSION', 'Infusion'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('GEL', 'Gel'), ('DROPS', 'Drops'), ('SUPPOSITORY', 'Suppository'), ('INHALER', 'Inhaler'), ('PATCH', 'Patch'), ('POWDER', 'Powder'), ('SOLUTION', 'Solution'), ('DEVICE', 'Medical device'), ('CONSUMABLE', 'Consumable'), ('OTHER', 'Other')], default='TABLET', max_length=20, verbose_name='dosage form')),
                ('pack_size', models.CharField(blank=True, help_text='For example: box of 100 tablets', max_length=64, verbose_name='pack size')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='reference unit cost')),
                ('selling_price', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='selling price')),
                ('wholesale_price', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), help_text='Price applied to institutional customers, if different.', max_digits=18, verbose_name='wholesale price')),
                ('vat_rate', apps.core.fields.PercentField(decimal_places=4, default=Decimal('18'), help_text='Set to 0 for exempt or zero-rated products.', max_digits=7, verbose_name='VAT rate (%)')),
                ('is_vat_exempt', models.BooleanField(default=False, help_text='Many essential medicines are exempt; this overrides the rate.', verbose_name='VAT exempt')),
                ('reorder_level', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='reorder level')),
                ('safety_stock', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='safety stock')),
                ('max_stock_level', apps.core.fields.QuantityField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='maximum stock level')),
                ('expiry_alert_days', models.PositiveIntegerField(default=180, verbose_name='expiry alert (days)')),
                ('storage_condition', models.CharField(choices=[('AMBIENT', 'Ambient (15–25 °C)'), ('COOL', 'Cool (8–15 °C)'), ('REFRIGERATED', 'Refrigerated (2–8 °C)'), ('FROZEN', 'Frozen (below 0 °C)'), ('PROTECT_LIGHT', 'Protect from light'), ('DRY', 'Keep dry')], default='AMBIENT', max_length=20, verbose_name='storage condition')),
                ('storage_notes', models.CharField(blank=True, max_length=255, verbose_name='storage notes')),
                ('requires_prescription', models.BooleanField(default=False, verbose_name='prescription required')),
                ('is_controlled', models.BooleanField(default=False, help_text='Subject to reinforced traceability requirements.', verbose_name='controlled substance')),
                ('atc_code', models.CharField(blank=True, max_length=16, verbose_name='ATC code')),
                ('registration_number', models.CharField(blank=True, max_length=64, verbose_name='marketing authorisation number')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='barcode')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending approval')], db_index=True, default='ACTIVE', max_length=16, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='catalog.category', verbose_name='category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='catalog.manufacturer', verbose_name='manufacturer')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='catalog.unitofmeasure', verbose_name='unit of measure')),
            ],
            options={
                'verbose_name': 'medicine',
                'verbose_name_plural': 'medicines',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_unit_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='previous cost')),
                ('new_unit_cost', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='new cost')),
                ('old_selling_price', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='previous selling price')),
                ('new_selling_price', apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='new selling price')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='effective from')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_changes', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.medicine', verbose_name='medicine')),
            ],
            options={
                'verbose_name': 'price history entry',
                'verbose_name_plural': 'price history',
                'ordering': ('-effective_from',),
                'indexes': [models.Index(fields=['medicine', '-effective_from'], name='catalog_pri_medicin_a36979_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['status', 'name'], name='idx_medicine_status_name'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['category', 'status'], name='idx_medicine_category'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['generic_name'], name='idx_medicine_generic'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', Decimal('0'))), name='medicine_selling_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', Decimal('0'))), name='medicine_unit_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('max_stock_level', Decimal('0')), ('max_stock_level__gte', models.F('reorder_level')), _connector='OR'), name='medicine_max_stock_above_reorder'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('barcode', ''), _negated=True)), fields=('barcode',), name='unique_active_barcode'),
        ),
    ]
