"""
Bilingual product/category text, plus batch capture on the product form.

Written by hand rather than autogenerated: the autodetector reads `name` ->
`name_fr` as a drop-and-add, which would discard every existing product name.
RenameField keeps the column data intact.

The status/name index is dropped before the rename and recreated after, since
an index cannot outlive the column it is defined on.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        # --- Drop indexes that reference the columns being renamed ---------
        migrations.RemoveIndex(
            model_name="medicine",
            name="idx_medicine_status_name",
        ),
        migrations.AlterModelOptions(
            name="medicine",
            options={
                "ordering": ("name_fr",),
                "verbose_name": "medicine",
                "verbose_name_plural": "medicines",
            },
        ),

        # --- Category: description becomes a bilingual pair ----------------
        migrations.RenameField(
            model_name="category",
            old_name="description",
            new_name="description_fr",
        ),
        migrations.AlterField(
            model_name="category",
            name="description_fr",
            field=models.TextField(blank=True, verbose_name="description (French)"),
        ),
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="description (English)"),
        ),

        # --- Medicine: four text fields become bilingual pairs -------------
        migrations.RenameField(
            model_name="medicine", old_name="name", new_name="name_fr",
        ),
        migrations.RenameField(
            model_name="medicine", old_name="brand_name", new_name="brand_name_fr",
        ),
        migrations.RenameField(
            model_name="medicine", old_name="strength", new_name="strength_fr",
        ),
        migrations.RenameField(
            model_name="medicine", old_name="notes", new_name="notes_fr",
        ),
        migrations.AlterField(
            model_name="medicine",
            name="name_fr",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="commercial name (French)"
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="brand_name_fr",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="brand name (French)"
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="strength_fr",
            field=models.CharField(
                blank=True, help_text="For example: 500 mg, 250 mg/5 ml",
                max_length=64, verbose_name="strength (French)",
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="notes_fr",
            field=models.TextField(blank=True, verbose_name="notes (French)"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="name_en",
            field=models.CharField(
                blank=True, db_index=True, max_length=200,
                verbose_name="commercial name (English)",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="brand_name_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="brand name (English)"
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="strength_en",
            field=models.CharField(
                blank=True, help_text="For example: 500 mg, 250 mg/5 ml",
                max_length=64, verbose_name="strength (English)",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="notes_en",
            field=models.TextField(blank=True, verbose_name="notes (English)"),
        ),

        # --- Batch / expiry captured at product entry ----------------------
        migrations.AddField(
            model_name="medicine",
            name="batch_number",
            field=models.CharField(blank=True, max_length=64, verbose_name="batch number"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="expiry date"),
        ),

        # --- Recreate the index against the renamed column -----------------
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["status", "name_fr"], name="idx_medicine_status_name_fr"
            ),
        ),
    ]
