# Generated by Django 5.1.5 on 2026-08-01 13:36

import apps.core.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_vat_inclusive_catalogue_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='selling_price',
            field=apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), help_text='The price the customer pays, with VAT included.', max_digits=18, verbose_name='selling price (VAT incl.)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='wholesale_price',
            field=apps.core.fields.MoneyField(decimal_places=4, default=Decimal('0'), help_text='Price applied to institutional customers, if different. VAT-inclusive, like the standard selling price.', max_digits=18, verbose_name='wholesale price (VAT incl.)'),
        ),
    ]
