# Generated by Django 5.1.5 on 2026-07-26 05:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_fr', models.CharField(max_length=200, verbose_name='title (French)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='title (English)')),
                ('body_fr', models.TextField(verbose_name='body (French)')),
                ('body_en', models.TextField(blank=True, verbose_name='body (English)')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='severity')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='visible from')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='visible until')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('target_roles', models.ManyToManyField(blank=True, help_text='Leave empty to broadcast to every user.', related_name='announcements', to='accounts.role', verbose_name='target roles')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcements',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(choices=[('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock'), ('EXPIRING_SOON', 'Expiring medicines'), ('EXPIRED', 'Expired medicines'), ('PO_APPROVAL_REQUEST', 'Purchase order approval request'), ('PO_APPROVED', 'Purchase order approved'), ('PO_REJECTED', 'Purchase order rejected'), ('STOCK_DISCREPANCY', 'Stock discrepancy'), ('INVOICE_DUE', 'Invoice due'), ('INVOICE_OVERDUE', 'Invoice overdue'), ('CREDIT_LIMIT_REACHED', 'Credit limit reached'), ('AUDIT_CHAIN_BROKEN', 'Audit integrity failure'), ('LICENCE_EXPIRING', 'Customer licence expiring'), ('SYSTEM_ANNOUNCEMENT', 'System announcement')], db_index=True, max_length=32, verbose_name='code')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='severity')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('link', models.CharField(blank=True, help_text='Frontend route the notification points to.', max_length=255, verbose_name='link')),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='dismissed at')),
                ('emailed_at', models.DateTimeField(blank=True, null=True, verbose_name='emailed at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='idx_notif_recipient_read'), models.Index(fields=['recipient', '-created_at'], name='idx_notif_recipient_date'), models.Index(fields=['dedupe_key', '-created_at'], name='idx_notif_dedupe')],
            },
        ),
    ]
