# Generated by Django 5.1.5 on 2026-08-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='code',
            field=models.CharField(choices=[('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock'), ('EXPIRING_SOON', 'Expiring medicines'), ('EXPIRED', 'Expired medicines'), ('PO_APPROVAL_REQUEST', 'Purchase order approval request'), ('PO_APPROVED', 'Purchase order approved'), ('PO_REJECTED', 'Purchase order rejected'), ('STOCK_DISCREPANCY', 'Stock discrepancy'), ('INVOICE_DUE', 'Invoice due'), ('INVOICE_OVERDUE', 'Invoice overdue'), ('CREDIT_LIMIT_REACHED', 'Credit limit reached'), ('OBR_DECLARATION_FAILED', 'OBR declaration failed'), ('AUDIT_CHAIN_BROKEN', 'Audit integrity failure'), ('LICENCE_EXPIRING', 'Customer licence expiring'), ('SYSTEM_ANNOUNCEMENT', 'System announcement')], db_index=True, max_length=32, verbose_name='code'),
        ),
    ]
